language: java
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - the.na4ig@gmail.com
    on_success: never # default: change
    on_failure: always # default: always